/**
 * Copyright (c) EMBL-EBI 2016
 */
(function downtimeMessage(){try{function showMessage(title,body,domains,paths){var matchPath=false,matchDomain=false;var i,pattern;for(i=0;i<domains.length;i++){domains[i]=domains[i].replace('.','\.');domains[i]=domains[i].replace('*','.*');domains[i]=domains[i].replace('?','.');domains[i]='^'+domains[i]+'$';pattern=new RegExp(domains[i],'');if(pattern.test(document.domain)){matchDomain=true;}}
for(i=0;i<paths.length;i++){paths[i]=paths[i].replace('.','\.');paths[i]=paths[i].replace('*','[^/]*');paths[i]=paths[i].replace('?','[^/]');paths[i]='^'+paths[i]+'/?$';pattern=new RegExp(paths[i],'');if(pattern.test(document.location.pathname)){matchPath=true;}}
if(!matchDomain||!matchPath){return;}
body=body.replace(/\*(.*?)\*/g,'<strong>$1</strong>');body=body.replace(/_(.*?)_/g,'<em>$1</em>');var downtime=document.createElement('div');downtime.className='downtime-message';downtime.innerHTML='<div class="downtime-message-inner"><p class="downtime-title">'+title+'</p><p class="downtime-message"><span class="downtime-note"></span> '+body+'</p></div>';var css='div.downtime-message { font-size:100%; padding:9px } '+'#contentsarea div.downtime-message { padding:0px } '+'div.downtime-message-inner { font-family: helvetica, sans-serif; padding:9px; border: 1px solid #CCC } '+'body.section-home.front div.downtime-message-inner { border: none; } '+'div.downtime-message p { margin:0 } '+'div.downtime-message p.downtime-title { font-size: 1rem; } '+'div.downtime-message p.downtime-message span.downtime-note { font-weight:bold } '+'div.downtime-message p.downtime-message strong { color:#e33e3e; font-weight:bold }'+'div.downtime-message p.downtime-message em { font-style:italic }';var head=(document.head||document.getElementsByTagName('head')[0]);var styles=document.createElement('style');styles.type='text/css';if(styles.styleSheet){styles.styleSheet.cssText=css;}else{styles.appendChild(document.createTextNode(css));}
head.appendChild(styles);var hasBreadcrumb=document.getElementById('breadcrumb')!==null;var contents=(document.getElementById('main')||document.getElementById('content')||document.getElementById('contentsarea'));if(hasBreadcrumb){var breadCrumb=document.getElementById('breadcrumb');contents.insertBefore(downtime,breadCrumb.nextSibling);}
else{contents.insertBefore(downtime,contents.childNodes[0]);}}}
catch(err){}})();